[project]
name = ""
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "faker==28.4.1",
    "numpy==2.1.1",
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.1",
    "six==1.16.0",
    "tzdata==2024.1",
]

[tool.uv]
package = false
